###################################################################################################
# This file defines a kubernetes service for fashionmnist model and externalizes the service
# using an Istio gateway, and a virtual service
#################################################################################################### fashionmnist service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: fashionmnist
  labels:
    app: fashionmnist
    service: fashionmnist
spec:
  ports:
  - port: 8501
    name: http
  selector:
    app: fashionmnist
---
#################################################################################################### Istio gateway
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fashionmnist-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
#################################################################################################### Istio virtualservice
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fashionmnist
spec:
  hosts:
  - "*"
  gateways:
  - fashionmnist-gateway
  http:
  - route:
    - destination:
        host: fashionmnist
        port:
          number: 8501