###################################################################################################
# This file defines a kubernetes service for fashionmnist model and externalizes the service
# using an Istio gateway, and a virtual service
#################################################################################################### fashionmnist service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: fashionmnist
  labels:
    app: fashionmnist
    service: fashionmnist
spec:
  ports:
  - port: 8501
    name: http
  selector:
    app: fashionmnist
---
#################################################################################################### Istio gateway
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fashionmnist-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "fashionmnist.com"
---
#################################################################################################### Istio virtualservice
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    iter8-tools/router: fashionmnist.iter8router
    iter8-tools/role: stable
  name: fashionmnist
spec:
  gateways:
  - mesh
  - fashionmnist-gateway
  hosts:
  - fashionmnist
  - "fashionmnist.com"
  http:
  - route:
    - destination:
        host: fashionmnist
        port:
          number: 8501
        subset: iter8-stable
      weight: 100
---
#################################################################################################### Istio destination rule
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
    iter8-tools/router: fashionmnist.iter8router
    iter8-tools/role: stable
  name: fashionmnist
spec:
  host: fashionmnist
  subsets:
  - labels:
      app: fashionmnist
      version: v1
    name: iter8-stable
