apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: fashionmnist-v3-rollout
spec:
  service:
    name: fashionmnist
    baseline: fashionmnist-v2
    candidates:
      - fashionmnist-v3
  networking:
    hosts:
      - name: fashionmnist.com
        gateway: fashionmnist-gateway
    id: fashionmnist.iter8router    
  criteria:
    - metric: iter8_mean_latency
      threshold:
        type: absolute
        value: 200
  duration:
    maxIterations: 20
    interval: 15s
  trafficControl:
    maxIncrement: 10
  cleanup: true
