apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: fashionmnist-v1-rollout
spec:
  service:
    name: fashionmnist
    baseline: fashionmnist-v3
    candidates:
      - fashionmnist-v1
  networking:
    hosts:
      - name: fashionmnist.com
        gateway: fashionmnist-gateway
    id: fashionmnist.iter8router    
  criteria:
    - metric: iter8_mean_latency
      threshold:
        type: absolute
        value: 100
  duration:
    maxIterations: 8
    interval: 15s
  trafficControl:
    maxIncrement: 20
  cleanup: true
