##################################################################################################
# This file defines the deployment for the fashionmnist model version v3
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashionmnist-v3
  labels:
    app: fashionmnist
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashionmnist
      version: v3
  template:
    metadata:
      labels:
        app: fashionmnist
        version: v3
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: fashionmnist
        image: docker.io/iter8/fashionmnist:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501